# Generated by Django 4.1.2 on 2022-10-27 06:14

import aws_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeAccount_aws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('token', models.CharField(blank=True, max_length=1000, null=True)),
                ('credentials', aws_app.models.CredentialsField(null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('expiry', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
