# change password
PASSWORD_CHANGES = "Password changed Successfully."
PASSWORD_CONFIRM_PASSWORD_ERROR = (
    "Password and Confirm Password do not match or are not correct."
)
INCORRECT_PASSWORD = "Existing password is Invalid."

# login
LOGIN_SUCCESS_MESSAGE = "Logged In SuccessFully."
INVALID_USERNAME_PASSWORD_MESSAGE = "Please Check Your Email/Password ."

# log out
LOGOUT_SUCCESS_MESSAGE = "Logged out Successfully."

# forgot password
EMAIL_SEND_MESSAGE = (
    "A password reset email has been Successfully sent to your email address."
)
EMAIL_SEND_ERROR_MESSAGE = "An Error occured while sending password reset email."
ACCOUNT_INACTIVE = "You account is not active. Please contact our support team."
USER_NOT_EXISTS = "User does not exists."
INVALID_EMAIL = "Please enter valid email"

# Sign UP
USER_CREATED_MESSAGE = "User Created Successfully."
ERROR_CREATING_USER = "Something went wrong while Creating User, please try again."
EMAIL_ALREADY_EXISTS = "That email address is already in use."
PASSWORD_MISMATCHED = "Passwords do not match."
INVALID_SIGNUP_INPUTS = (
    "The entered information is invalid, please enter Valid Inputs and try again."
)

# Account update
UPDATED_SUCCESSFULLY = "Account updated successfully."
ERROR_UPDATING = "An unknown error occurred, please try again with correct info."
MISSING_UPDATE_FIELDS = "There was an issue updating your account, make sure entered email and timezone are correct!"

# otp
OTP_REQUIRED_MESSAGE = "Please provide the OTP to continue."

# update
ACCOUNT_INFO_UPDATE = "Account info successfully updated."

# COUNTRIES = sorted(['Brunei', 'Macau', 'Taiwan', 'Mongolia', 'China', 'Malaysia', 'Hong Kong', 'Singapore',
#                     'Philippines', 'United Arab Emirates', 'Armenia', 'Mauritius', 'Seychelles', 'Oman',
#                     'Azerbaijan', 'Réunion', 'Georgia', 'Western Sahara', 'Jersey', 'Ireland', 'Congo (Rep.)',
#                     'Cameroon', 'Morocco', 'Central African Rep.', 'Guernsey', 'Algeria', 'Isle of Man',
#                     'Angola', 'Portugal', 'Niger', 'Gabon', 'Tunisia', 'Congo (Dem. Rep.)', 'Faroe Islands',
#                     'Chad', 'Nigeria', 'Britain (UK)', 'Equatorial Guinea', 'Benin', 'Australia',
#                     'South Georgia & the South Sandwich Islands', 'St Pierre & Miquelon', 'Brazil', 'Suriname',
#                     'French Guiana', 'Argentina', 'Uruguay', 'Falkland Islands', 'Bermuda', 'Canada', 'Belize',
#                     'Nicaragua', 'El Salvador', 'Costa Rica', 'Honduras', 'Guatemala', 'Tokelau',
#                     'Samoa (western)', 'Tonga', 'Northern Mariana Islands', 'Guam', 'Papua New Guinea',
#                     'Micronesia', 'Laos', 'Christmas Island', 'Cambodia', 'Thailand', 'Indonesia', 'Vietnam',
#                     'Lebanon', 'Syria', 'Turkey', 'Romania', 'Latvia', 'Iraq', 'Mayotte', 'Åland Islands',
#                     'Comoros', 'Kenya', 'Belarus', 'Cyprus', 'Estonia', 'Palestine', 'Qatar',
#                     'Tanzania', 'Kuwait', 'Yemen', 'Somalia', 'Finland', 'Djibouti', 'Moldova', 'Madagascar',
#                     'Greece', 'Lithuania', 'Bulgaria', 'Eritrea', 'Israel', 'Jordan', 'South Sudan', 'Ukraine',
#                     'Bahrain', 'Ethiopia', 'Saudi Arabia', 'Uganda', 'Guinea-Bissau', 'Togo', "Côte d'Ivoire",
#                     'Sao Tome & Principe', 'St Helena', 'Iceland', 'Senegal', 'Guinea', 'Burkina Faso',
#                     'Greenland', 'Gambia', 'Sierra Leone', 'Mauritania', 'Liberia', 'Mali', 'Ghana',
#                     'Kazakhstan', 'Kyrgyzstan', 'British Indian Ocean Territory', 'Bangladesh', 'Bhutan',
#                     'Myanmar (Burma)', 'Cocos (Keeling) Islands', 'Dominica', 'Haiti', 'Martinique',
#                     'Bahamas', 'Puerto Rico', 'Virgin Islands (US)', 'St Vincent', 'Venezuela', 'St Lucia',
#                     'Turks & Caicos Is', 'United States', 'St Barthelemy', 'Curaçao', 'St Martin (French)',
#                     'St Maarten (Dutch)', 'Trinidad & Tobago', 'Dominican Republic', 'Guyana', 'Grenada',
#                     'Aruba', 'Cuba', 'Barbados', 'Montserrat', 'Virgin Islands (UK)', 'Anguilla',
#                     'St Kitts & Nevis', 'Guadeloupe', 'Bolivia', 'Paraguay', 'Chile', 'Caribbean NL',
#                     'Antigua & Barbuda', 'French Polynesia', 'Cook Islands', 'Wallis & Futuna', 'Antarctica',
#                     'Marshall Islands', 'Tuvalu', 'New Zealand', 'Fiji', 'Kiribati', 'Nauru', 'Korea (North)',
#                     'Nepal', 'Japan', 'Palau', 'Korea (South)', 'East Timor', 'Sri Lanka', 'India', 'Cape Verde',
#                     'Turkmenistan', 'Pitcairn', 'Tajikistan', 'Uzbekistan', 'Maldives',
#                     'French Southern & Antarctic Lands', 'Iran', 'Afghanistan', 'Mexico', 'Panama',
#                     'Cayman Islands', 'Colombia', 'Ecuador', 'Peru', 'Jamaica', 'Pitcairn', 'Namibia',
#                     'Gibraltar', 'Switzerland', 'Libya', 'Eswatini (Swaziland)', 'Netherlands', 'Malawi',
#                     'Norway', 'Serbia', 'Slovakia', 'Zambia', 'Austria', 'Czech Republic', 'Sweden',
#                     'Mozambique', 'Luxembourg', 'Croatia', 'Vatican City', 'France', 'Montenegro', 'Slovenia',
#                     'Rwanda', 'Denmark', 'Belgium', 'Russia', 'Malta', 'Germany', 'South Africa', 'Andorra',
#                     'Albania', 'Svalbard & Jan Mayen', 'Spain', 'North Macedonia', 'Liechtenstein',
#                     'San Marino', 'Zimbabwe', 'Lesotho', 'Burundi', 'Botswana', 'Italy', 'Hungary', 'Monaco',
#                     'Poland', 'Bosnia & Herzegovina', 'Egypt', 'Sudan', 'Samoa (American)',
#                     'US minor outlying islands', 'Niue', 'Solomon Islands', 'Norfolk Island', 'Vanuatu',
#                     'New Caledonia'])

COUNTRIES = [
    "Argentina",
    "Brazil",
    "Canada",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Mexico",
    "Paraguay",
    "United States",
    "Australia",
    "Hong Kong",
    "India",
    "Indonesia",
    "Japan",
    "Kazakhstan",
    "Malaysia",
    "New Zealand",
    "Philippines",
    "Singapore",
    "South Korea",
    "Taiwan",
    "Thailand",
    "Vietnam",
    "Israel",
    "Libya",
    "Nigeria",
    "South Africa",
    "United Arab Emirates",
    "Albania",
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Latvia",
    "Luxembourg",
    "Moldova",
    "Netherlands",
    "North Macedonia",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Russia",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "Ukraine",
    "United Kingdom"
]


VPN_COUNTRIES = [
    "Argentina",
    "Brazil",
    "Canada",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Mexico",
    "Paraguay",
    "United States",
    "Australia",
    "Hong Kong",
    "India",
    "Indonesia",
    "Japan",
    "Kazakhstan",
    "Malaysia",
    "New Zealand",
    "Philippines",
    "Singapore",
    "South Korea",
    "Taiwan",
    "Thailand",
    "Vietnam",
    "Israel",
    "Libya",
    "Nigeria",
    "South Africa",
    "United Arab Emirates",
    "Albania",
    "Austria",
    "Belgium",
    "Bosnia &amp; Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Latvia",
    "Luxembourg",
    "Moldova",
    "Netherlands",
    "North Macedonia",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Russia",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "Ukraine",
    "United Kingdom",
]


ABOUT_CATEGORY = [
    "Arts and Culture",
    "Autos",
    "Business",
    "College/University",
    "Community",
    "Computers",
    "Directories",
    "Education",
    "Entertainment",
    "Events",
    "fashion",
    "Finance",
    "Food",
    "Games",
    "Health",
    "Home",
    "Internet",
    "Kids and Teens",
    "Law and Lawyers",
    "Legal",
    "Lifestyle",
    "Marketing",
    "Music",
    "News and Media",
    "Personals",
    "Real Estate",
    "Recreation and Free Time",
    "Refrence",
    "Regional",
    "Science",
    "Shopping",
    "Society and Culture",
    "Sports",
    "Travel and Tourism",
    "Other",
]

SMS_COUNTRIES = (
    ("ru", "Russian Federation"),
    ("kz", "Kazakhstan"),
    ("ua", "Ukraine"),
    ("ht", "Haiti"),
    ("ro", "Romania"),
    ("ar", "Argentina"),
    ("by", "Belarus"),
    ("ba", "Bos. and Herz."),
    ("br", "Brazil"),
    ("kh", "Cambodia"),
    ("ca_v", "Canada (Virtual)"),
    ("cl", "Chile"),
    ("co", "Colombia"),
    ("hr", "Croatia"),
    ("cy", "Cyprus"),
    ("do", "Dominicana"),
    ("eg", "Egypt (Virtual)"),
    ("ee", "Estonia"),
    ("fi", "Finland"),
    ("fr", "France"),
    ("ge", "Georgia"),
    ("de", "Germany"),
    ("id", "Indonesia"),
    ("il", "Israel"),
    ("ke", "Kenya"),
    ("xk", "Kosovo"),
    ("kg", "Kyrgyzstan"),
    ("la", "Laos"),
    ("lv", "Latvia"),
    ("lt", "Lithuania"),
    ("my", "Malaysia"),
    ("mx", "Mexico"),
    ("ma", "Morocco"),
    ("nl", "Netherlands"),
    ("nz", "New Zealand"),
    ("py", "Paraguay"),
    ("ph", "Philippines"),
    ("pl", "Poland"),
    ("pt", "Portugal"),
    ("za", "South Africa"),
    ("es", "Spain"),
    ("se", "Sweden"),
    ("uk", "United Kingdom"),
    ("us", "United States"),
    ("us3", "USA (Virtual)"),
    ("vn", "Vietnam"),
)
