SURFSHARK_COUNTRIES = {
    "Albania": "al-tia.prod.surfshark.com_udp.ovpn",
    "Argentina": "ar-bua.prod.surfshark.com_udp.ovpn",
    "Austria": "at-vie.prod.surfshark.com_udp.ovpn",
    "Azerbaijan": "az-bak.prod.surfshark.com_udp.ovpn",
    "Belgium": "be-bru.prod.surfshark.com_udp.ovpn",
    "Bosnia & Herzegovina": "ba-sjj.prod.surfshark.com_udp.ovpn",
    "Brazil": "br-sao.prod.surfshark.com_udp.ovpn",
    "Bulgaria": "bg-sof.prod.surfshark.com_udp.ovpn",
    "Chile": "cl-san.prod.surfshark.com_udp.ovpn",
    "Colombia": "co-bog.prod.surfshark.com_udp.ovpn",
    "Costa Rica": "cr-sjn.prod.surfshark.com_udp.ovpn",
    "Croatia": "hr-zag.prod.surfshark.com_udp.ovpn",
    "Cyprus": "cy-nic.prod.surfshark.com_udp.ovpn",
    "Czech Republic": "cz-prg.prod.surfshark.com_udp.ovpn",
    "Denmark": "dk-cph.prod.surfshark.com_udp.ovpn",
    "Estonia": "ee-tll.prod.surfshark.com_udp.ovpn",
    "Finland": "fi-hel.prod.surfshark.com_udp.ovpn",
    "Greece": "gr-ath.prod.surfshark.com_udp.ovpn",
    "Hong Kong": "hk-hkg.prod.surfshark.com_udp.ovpn",
    "Hungary": "hu-bud.prod.surfshark.com_udp.ovpn",
    "Iceland": "is-rkv.prod.surfshark.com_udp.ovpn",
    "Indonesia": "id-jak.prod.surfshark.com_udp.ovpn",
    "Ireland": "ie-dub.prod.surfshark.com_udp.ovpn",
    "Israel": "il-tlv.prod.surfshark.com_udp.ovpn",
    "Japan": "jp-tok.prod.surfshark.com_udp.ovpn",
    "Kazakhstan": "kz-ura.prod.surfshark.com_udp.ovpn",
    "Latvia": "lv-rig.prod.surfshark.com_udp.ovpn",
    "Luxembourg": "lu-ste.prod.surfshark.com_udp.ovpn",
    "Malaysia": "my-kul.prod.surfshark.com_udp.ovpn",
    "Mexico": "mx-mex.prod.surfshark.com_udp.ovpn",
    "Moldova": "md-chi.prod.surfshark.com_udp.ovpn",
    "Netherlands": "nl-ams.prod.surfshark.com_udp.ovpn",
    "New Zealand": "nz-akl.prod.surfshark.com_udp.ovpn",
    "Nigeria": "ng-lag.prod.surfshark.com_udp.ovpn",
    "North Macedonia": "mk-skp.prod.surfshark.com_udp.ovpn",
    "Norway": "no-osl.prod.surfshark.com_udp.ovpn",
    "Paraguay": "py-asu.prod.surfshark.com_udp.ovpn",
    "Philippines": "ph-mnl.prod.surfshark.com_udp.ovpn",
    "Romania": "ro-buc.prod.surfshark.com_udp.ovpn",
    "Russia": "ru-mos.prod.surfshark.com_udp.ovpn",
    "Serbia": "rs-beg.prod.surfshark.com_udp.ovpn",
    "Singapore": "sg-sng.prod.surfshark.com_udp.ovpn",
    "Slovakia": "sk-bts.prod.surfshark.com_udp.ovpn",
    "Slovenia": "si-lju.prod.surfshark.com_udp.ovpn",
    "South Africa": "za-jnb.prod.surfshark.com_udp.ovpn",
    "South Korea": "kr-seo.prod.surfshark.com_udp.ovpn",
    "Vietnam": "vn-hcm.prod.surfshark.com_udp.ovpn",
    "Sweden": "se-sto.prod.surfshark.com_udp.ovpn",
    "Switzerland": "ch-zur.prod.surfshark.com_udp.ovpn",
    "Taiwan": "tw-tai.prod.surfshark.com_udp.ovpn",
    "Thailand": "th-bkk.prod.surfshark.com_udp.ovpn",
    "Turkey": "tr-ist.prod.surfshark.com_udp.ovpn",
    "Ukraine": "ua-iev.prod.surfshark.com_udp.ovpn",
    "United Arab Emirates": "ae-dub.prod.surfshark.com_udp.ovpn",
    "Chennai": "in-chn.prod.surfshark.com_udp.ovpn",
    "Mumbai": "in-mum.prod.surfshark.com_udp.ovpn",
    "Indore": "in-idr.prod.surfshark.com_udp.ovpn",
}

access_key = "1361304377525370881-sluCDqfvWV6lYMPmE0Cwzdzij4Htv1"
secret_key = "o5Ba2Amm4RlN4x3f7ShBRvdWEpiQM2arKjbAFsq9A7syc"

TWITTER_COMMENTS = [
    "What are you guys still waiting for? This is going to be outstanding",
    "This is a very excellent project",
    "Join this good and reliable project, don't miss, join now to participate in the project",
    "Super projectHeading to the mooon Thanks for the opportunity",
    "Please guys let's make this free coin together",
    "This is cool and you wouldn't want to miss out...",
    "Wonderful project. This gonna rule the world soon",
    "Great project with great prospect",
    "What an amazing project keep moving to the moon",
    "No one should miss this opportunity",
    "I'm seeing the fun in the games already.",
    "I'm very excited for this strong project",
    "I hope this project is a success, sir and then it becomes one of the best",
    "It's a very strong project. I think it will give a big profit in future. So, please join",
    "Very nice project and a very strong  team behind",
    "I am very happy to see such a beautiful project. I hope its future is very bright. This project is one of the best projects in favor of grace.",
    "Congratulations, I hope the project will progress and the project will be more successful",
    "I'm looking forward to this project.",
    "Bro... legitimately one of the coolest things I've ever seen",
    "Oh, I really like cute stuff I wish I can have it on my collection.",
    "Great product, innovative technology. $xyz, the future is yours!",
    "Can't wait to see Tim's #NFT collection!",
    "Hello, This is the TRUST WALLET Help Desk, Send a Direct message explaining your issue and kindly follow back so that I can assist you",
    "Real project. Together we strong!!!",
    "This is real-time data. Organics makes perfect",
    "A master's work. Well done",
    "I love your NFTs! You have a wonderfully unique idea.",
    "This project is good and helpful for the future.",
    "Amazing platform for earn money via doing almost nothing",
    "One of the best Roadmaps I've seen for a crypto. you definitely has high potential",
    "Don't Sleep on this !! Real Defi !!",
    "Well designed projects, a good and reliable team, Probably the best investment",
    "This is a wonderful project and, of course, it will have a bright future. Good luck!",
    "Project With Great Idea...... I advise everyone not to slow down and to join the project. I'm sure the project will be successful! Good Luck my friends....!!",
    "Can't wait for more updates",
    "I am really surprised. Suddenly see your application. This is really wonderful project. Have a nice day. God Bless You.",
    "This was a good partnership, I hope they keep on it, Also BSC is kinda booming now",
    "Hello sir, I suddenly see your project. & I am impressed",
    "With more progress and success, God willing, greater expansion in the field and financial transactions, and a greater investment volume.",
    "Wow awesome video I really like this video I appreciate thanks for sharing this awesome video with us good job keep it up",
    "Wow, cool! Keep working guys! All support for your team!",
    "I bet they're going to replace the sun WITH A MOON",
    "Don't miss it guys and good luck with this awesome NFTs",
    "Origin City! That's a great price! Welcome to the world!",
    "At this time a great project for crypto assets. I wish the owners and staff a healthy and successful life for your company. Best wishes for this project",
    "Hope we see not late to the party",
    "I Think, this is a very strong project Thanks for sharing this wonderful opportunity Best wishes for all team member",
    "Thank you so much for giving us this great opportunity. We are all so excited about this great event",
    "This is gonna be a great and awesome project, with the liquidity and others, Great Project! Hope this project is a success I'm so enthusiast",
    "This is a great project, built with careful planning, and on the run with a great concept by a great team. project with a higher return on investment.",
    "Origin City! That's a great price! Welcome to the world!",
    "At this time a great project for crypto assets. I wish the owners and staff a healthy and successful life for your company.",
    "Best wishes for this project",
    "Hope we see not late to the party",
    "I Think, this is a very strong project Thanks for sharing this wonderful opportunity Best wishes for all team member",
    "Thank you so much for giving us this great opportunity. We are all so excited about this great event",
    "This is gonna be a great and awesome project, with the liquidity and others",
    "Great Project! Hope this project is a success I'm so enthusiast",
    "This is a great project, built with careful planning, and on the run with a great concept by a great team. project with a higher return on investment.",
    "You looks really good and cute✨♬I’m falling in love with you 😀",
    "I love you from the core of my heart ♡",
    "She's so cute????????????",
    "Ahhhmazing💕",
    "I was surprised🤪 it looks like a hedgehog❗ but it becomes more and more beautiful with this😉",
    "How can you maintain yourself like this🤣? And that hairstyle is really nice!!!!",
    "Where are you from?",
    "Hello Hottie!🤩",
    "😘😘😍❤️💕💗💜💜💖💖😘🤩 so beautiful and I love you",
    "What are you guys still waiting for? This is going to be outstanding",
    "This is a very excellent project",
    "That's true right. I mean, it's too sexy and too cute😍😍😍😍😍💘",
    "Good evening❗ that's really 😭 isn't ?💓💓💓",
    "Stunning!!!",
    "Fabolous 💖",
    "Beautiful ✨ style sounds good❤️",
    "It's so cute💕💕💕💕💕",
    "😋😋😋😋😋",
    "Check DM! Please reply to me!",
    "Hello!✨",
    "So sexy!💖",
    "Loads of love😘😘😍❤️",
    "Join this good and reliable project, don't miss, join now to participate in the project",
    "Super project Heading to the moon Thanks for the opportunity",
    "Please guys let's make this free coin together",
    "This is cool and you wouldn't want to miss out...",
    "Wonderful project. This gonna rule the world soon",
    "Great project with great prospect",
    "What an amazing project keep moving to the moon",
    "No one should miss this opportunity",
    " I'm seeing the fun in the games already.",
    " I'm very excited for this strong project",
    "I hope this project is a success, sir and then it becomes one of the best",
    " It’s a very strong project. I think it will give a big profit in future. So, please join",
    "Very nice project and a very strong team behind",
    " I am very happy to see such a beautiful project. I hope its future is very bright. This project is one of the best projects in favor of grace.",
    "Congratulations, I hope the project will progress and the project will be more successful",
    " I'm looking forward to this project.",
    "Bro... legitimately one of the coolest things I’ve ever seen",
    "Oh, I really like cute stuff I wish I can have it in my collection.",
    "Great product, innovative technology. $xyz, the future is yours!",
    "Can't wait to see Tim's #NFT collection!",
    "Hello, This is the TRUST WALLET Help Desk, Send a Direct message explaining your issue and kindly follow back so that I can assist you",
    "Real project. Together we strong!!!",
    "This is real-time data. Organics makes perfect",
    "A master's work. Well done",
    "I love your NFTs! You have a wonderfully unique idea.",
    "This project is good and helpful for the future.",
    "Amazing platform for earn money via doing almost nothing",
    "One of the best Roadmaps I've seen for a crypto. you definitely has high potential",
    "Don't Sleep on this !! Real Defi !!",
    "Well designed projects, a good and reliable team, Probably the best investment",
    "This is a wonderful project and, of course, it will have a bright future. Good luck!",
    " Project With Great Idea...... I advise everyone not to slow down and to join the project. I'm sure the project will be successful! Good Luck my friends....!!",
    " Can't wait for more updates",
    " I am really surprised. Suddenly see your application. This is really wonderful project. Have a nice day. God Bless You.",
    "This was a good partnership, I hope they keep on it, Also BSC is kinda booming now",
    "Hello sir, I suddenly see your project. & I am impressed",
    "With more progress and success, God willing, greater expansion in the field and financial transactions, and a greater investment volume.",
    "Wow awesome video I really like this video I appreciate thanks for sharing this awesome video with us good job keep it up",
    "Wow, cool! Keep working guys! All support for your team!",
    "I bet they're going to replace the sun WITH A MOON",
    "Don't miss it guys and good luck with this awesome NFTs",
    "Origin City! That's a great price! Welcome to the world!",
    "At this time a great project for crypto assets. I wish the owners and staff a healthy and successful life for your company.",
    "Best wishes for this project",
    "Hope we see not late to the party",
    "I Think, this is a very strong project Thanks for sharing this wonderful opportunity Best wishes for all team member",
    "Thank you so much for giving us this great opportunity. We are all so excited about this great event",
    "This is gonna be a great and awesome project, with the liquidity and others,",
    "Great Project! Hope this project is a success I'm so enthusiast",
    "This is a great project, built with careful planning, and on the run with a great concept by a great team. project with a higher return on investment.",
    "I love you beautiful💓",
    "Why so cute?💘",
    "I really adore you😍",
    "It's cool💐",
    "It looks good on you💓💓💓💓💓💓",
    "Did you read French toast😆",
    "I could eat so much when I was a child❗ why can't I eat so much when I grow up😢",
    "She's so cute😍😍😍",
    "😎❤️😘😘",
    "I don’t disagree with the update or the results (maybe it’s good to have a bit of a clean slate) but communication is definitely important.",
    "This update should not affect the bids. Let us know if someone got any issues with that",
    "What changes have they made that you dont like?",
    "I think it may be free, not sure.",
    "on what platform should I mint my artworks?",
    "yeah, crazy growth",
    "Beautiful! Hope to see the next one",
    "very creative as always ",
    "Love it!!!!",
    "I’ll take that as a hint.",
    "Awesome!!! Any chance for a variation",
    "I want to ask you when u will sell this nft i mean people are bidding now..!! When are you gonna sell this  like is there anytime or any reserve price i am confused",
    "I still can’t believe it",
    "It's....it's beautiful!",
    "Thank you so much for your openness to collaboration.  It just makes the whole space so much better!!!",
    "no wayyy that’s too fucking dope lmao",
    "This is such freaking nice one, funny and gorgeous at the same time, love the reference too ! ",
    "That art is iconic",
    "I overslept everything This is just amazing news! The collaboration we deserve! Congratulations to you guys and good luck with that! ",
    "OH MY GOD! ",
    "Wow that's amazing man! You're going places! ",
    "Glad it brings you joy Sparkles",
    "Omg I LOVE this! ",
    "Huge congrats on that achievement!",
    "Pure awesomeness!",
    "Reflection on the shades",
    "WHAAAAT!! that is incredible!!!! Fo sho!",
    "This is something we call Cool!!!!!",
    "Good stuff! Great job!",
    "amazing! I love it",
    "Holy smoke, that's hilarious ",
    "Dude... Very cool. Congratulations.",
    "Well that’s just dope right there! ",
    "Too cool for skool.",
    "Love this sooooo much!",
    "That’s huge!",
    "All the very best for your new venture.",
    "Best wishes for your new business.",
    "Congratulations on your first move towards a great life.",
    "You will prosper and succeed, I believe in you.",
    "Wishing you the best of luck on starting new business.",
    "May you achieve all your goals and desires in life.",
    "I’m praying for your great and prosperous future.",
    "So happy to hear that you’ve finally taken the first step for your great future.",
    "My best wishes are always with you… Go ahead.",
    "You definitely will succeed, I trust you and your dedication.",
    "When I see you, I see just hard work and passion. All the best.",
    "You’re ambitious, but a hardworking ambitious.",
    "Hope for the best for you and the new business you are about to start.",
    "Luck and greater success are on your side, just keep going.",
    "Passion, dedication, and willingness to do something great. You’ve everything to start a new business.",
    "Your journey has been inspiring for me, and it always will be.",
    "May you tackle every challenge, and get the success you aim for.",
    "I share my best wishes for your new business.",
    "Good luck with your startup, and the first step towards a great life.",
    "I know you are not a dreamer, you are a doer.",
    "This is the boldest step towards your dreams.",
    "I appreciate you, starting your dream business.",
    "Congratulations on starting a new company.",
    "Good luck with your startup, Best wishes.",
    "Prayers for all the success that you’re dreaming of.",
    "May every day you get closure to your goals, All the best.",
    "You really will be a great leader for your team. I admire you.",
    "I’m a fan of your hard work and dedication.",
    "You’ve been giving your best always, and you will in the future, too.",
    "This is just the start of your great life, that you’re about to create.",
    "I wish you all the very best for your new business.",
    "You will reach your goals, sooner. I believe in you.",
    "Sending you my best wishes for your startup.",
    "You are a born entrepreneur and a true leader.",
    "Great wishes on your new adventure.",
    "My prayers for the success of your business.",
    "You are unstoppable. Great move.",
    "I want nothing more, just a party on your first big contract.",
    "May you’re a boss now, but you will prefer to be a leader. I know you.",
    "I’m so happy for you and the new business.",
    "Wish you great success, my friend.",
    "I’m feeling so proud of you, after knowing you’ve started a new business.",
    "There’s no one here to doubt your hard work and patience, ever.",
    "You are going great. Keep following your heart, friend.",
    "Congratulations. Be a great leader.",
    "That’s what I’m expecting from you, my friend.",
    "A big congratulations on taking the first step to greater life.",
    "May you create the best team that supports you well.",
    "Everyone thinks that you took a bold move, But I believe you.",
    "From our first meeting, I knew you’ve great business acumen.",
    "You are building something big, so all the best.",
    "This business is not only about you, this idea helps many people. Great job.",
    "I believe in you, you definitely will be successful. All the best.",
    "Best wishes on your new exciting journey.",
    "All the best for your startup.",
    "You’ll be successful. You’re business-minded.",
    "Blessing for your new path. You’ll reach there, soon.",
    "May your business grow that high, and set the new trends.",
    "You are a passionate and hard worker. And, that’s something I expect from you.",
    "Wishing you all the very best on your startup, and taking action on ideas.",
    "Best wishes for your future, you’ll achieve the success you dream of.",
    "May this new business bring a lot many happiness and growth opportunities.",
    "Keep it up, there’re many out there who are learning from you.",
    "You are an entrepreneur, but a dedicated one.",
    "May your all hard work and patience will pay off in your business.",
    "I’m really happy to know about your startup. All the very best.",
    "Welcome to the club of entrepreneurs.",
    "So glad to see you’re becoming your boss.",
    "That’s nothing more surprising, my best friend. I know you’re a leader.",
    "I am so confident about you, that you’ll achieve your goals way faster.",
    "Your idea is really impressive, I guarantee that this encourages many stories.",
    "I know you’re not supposed to do normal things. This one suits you, well.",
    "Congratulations on updating yourself. You are a businessman, I trust the most.",
    "Just never look back and keep going.",
    "I wish I could take the bold move as you. But, I glad you take this, my friend.",
    "All the Best. There’s something great coming at you.",
    "I’m sure this business will support many dreams.",
    "There’re tons of scope for your new business. Keep it up.",
    "You’re one of a kind!",
    "You’re inspiring.",
    "If you were a box of crayons, you’d be the giant name-brand one with the built-in sharpener.",
    "You should be thanked more often. So thank you!!",
    "Our community is better because you’re in it.",
    "Someone is getting through something hard right now because you’ve got their back.",
    "You have the best ideas.",
    "You always know how to find that silver lining.",
    "Everyone gets knocked down sometimes, but you always get back up and keep going.",
    "You’re a candle in the darkness.",
    "You’re a great example to others.",
    "You always know just what to say.",
    "You’re always learning new things and trying to better yourself, which is awesome.",
    "If someone based an Internet meme on you, it would have impeccable grammar.",
    "When you make a mistake, you fix it.",
    "Who raised you? They deserve a medal for a job well done.",
    "You’re great at figuring stuff out.",
    "You’re so thoughtful.",
    "Your creative potential seems limitless.",
    "Actions speak louder than words, and yours tell an incredible story.",
    "“Strength and growth come only through continuous effort and struggle.” – Napoleon Hill, author",
    "“Everyone wants to live on top of the mountain, but all the happiness and growth occurs while you’re climbing it.” – Andy Rooney, journalist",
    "“Mistakes are the growing pains of wisdom.” – William George Jordan, writer/editor",
    "“The greatest thing in this world is not so much where we stand as in what direction we are moving.” – Johann Wolfgang von Goethe, writer/statesman",
    "“And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom.” – Anaïs Nin, writer",
    "“The only way you are going to have success is to have lots of failures first.” – Sergey Brin, co-founder, Google",
    "“If you don’t build your dream, someone else will hire you to help them build theirs.” – Dhirubhai Ambani, founder, Reliance Industries",
    "“I do not know the word ‘quit.’ Either I never did, or I have abolished it.” – Susan Butcher, sled dog racer",
    "I like the way you're working.",
    "I like the way you've handled this.",
    "It looks like you've put a lot of work into this",
    "Keep it up.",
    "Excellent Keep up the good work.",
    "My goodness, how impressive!",
    "This shows fine improvement.",
    "Spectacular! This shows you've really been thinking.",
    "I see you as the most trustable and honest person in cryptoworld. Thats why I am an #binancian",
    "Misconceptions are like broken glass. We must be careful not to be harmed.",
    "You're an investor with vision. You see potential of the crypto coin you hold over the time.",
    "Interesting! I still think you trade sometimesThinking face, secretly buying more. ",
    "As you are a businessman, your net worth is your business duh",
    "All current chains would melt if any significant users on-boarded in a hurry.",
    "You def look like you still play Magic bro, no offense",
    "lol Oh my god huge selling, everyone wants a part of the nft pie",
    "Gaming is going to be the best use of NFTs.  Art was only the appetizer!",
    "How we didn't see that one coming! Dope!",
]


TWITTER_BIOS = [
    """#cryptoart & #NFT lover
✨ art curation and NFT collab✨ DMs open 🖤""",
    "Enthusiastic NFT Collector I see NFT, I buy NFT, Simply addicted #NFTCollectors",
    """Get ready for a new #NFT experience. Sharing daily curated NFTs.
#NFT #NFTCollectors #NFTs""",
    """This is the new creative marketplace. 🌐 Biggest NFT collab , Cryptoartists involved
#NFT #NFTCollectors #NFTs #Cryptoart
#cryptoart & #NFT lover""",
    """Eager NFT Collector. I see NFT, I purchase NFT, Really dependent
#NFTs #NFTCollectors""",
    """Prepare for another #NFT experience.
The Same is a multidisciplinary artist. Maker of New Face Collection.
Act naturally! #cryptoart & #NFT lover""",
    """Design • Collect • Sell • Each Edition digital art from leading artists and creators
around the world.
#blockchain #cryptoart #NFT """,
    """We share art in all its forms, adding a spark ✨ of creativity to your feed every day!
DMs open for Collab 🖤#NFTs #NFTCollectors """,
    """On a mission to bring more beauty to the world. ツ
#cryptoart #NFT""",
    #     """Creator ✦ Visual Artist ✦ Designer. Discover and collect digital artwork by some of
    # the world's most honored artists, illustrators, and designers. #NFTs #Cryptoart """,
]