# Generated by Django 3.1 on 2022-09-09 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import youtubebot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('token', models.CharField(blank=True, max_length=1000, null=True)),
                ('credentials', youtubebot.models.CredentialsField(null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
                ('expiry', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YoutubeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YoutubeVideoUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('video_url', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YoutubeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('video_url', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('LIKE', 'LIKE'), ('COMMENT', 'COMMENT'), ('DISLIKE', 'DISLIKE'), ('SUBSCRIBE', 'SUBSCRIBE'), ('VIEW_VIDEO', 'VIEW_VIDEO'), ('UPLOAD_VIDEO', 'UPLOAD_VIDEO')], max_length=100)),
                ('status', models.CharField(blank=True, choices=[('P', 'PENDING'), ('C', 'COMPLETED'), ('F', 'FAILED'), ('I', 'In-progress'), ('CN', 'CANCELED')], max_length=2, null=True)),
                ('view_video', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('channel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('group_status', models.JSONField(blank=True, null=True)),
                ('accounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtubebot.youtubeaccount')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtubebot.youtubegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='youtubeaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtubebot.youtubegroup'),
        ),
    ]
